### ISSUE TITLE
Review server security

### ISSUE THREAD

**Issue by DocV** [TheSoftwareFactory/lokki-server#65]
The server seems to have some security problems: for instance, the hashing function in locMapCommon.js is using salting incorrectly, which leaves our user accounts vulnerable to dictionary attacks if someone gets their hands on the list of hashed passwords. Somebody should figure out how the server handles security and authentication so that we can find potential issues and fix them.

**Comment by Grandi** [comment]
The comments in the code are kinda misleading because the function is actually used to hash email addresses rather than passwords. In my opinion the source needs a lot of refactoring before new features like individual salts would be wise to add. The code in locMapRESTAPI.js (handling authorization and signing up) is simply awful.

**Comment by ffagerho** [comment]
Please reopen this against the lokki-server repo.

**Comment by ffagerho** [comment]
It could be wise to spend a little bit of time to find specific security issues that could be improved, and opening specific issues for each.

**Comment by ffagerho** [comment]
Closing this because this is a constant task and there were already some improvements. Future security tasks should be more specific.
